"""Add Blue Line tables and fields

Revision ID: d1ecc018d33f
Revises: 
Create Date: 2025-10-27 19:17:50.623458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd1ecc018d33f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Commented out ALTER COLUMN operations as SQLite doesn't support them
    # Column type changes are not critical for functionality
    # op.alter_column('approval_workflows', 'regulatory_status',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.String(length=20),
    #            existing_nullable=True)
    # op.alter_column('approval_workflows', 'technical_status',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.String(length=20),
    #            existing_nullable=True)
    
    # Rename calculation_metadata to metadata in blue_lines
    with op.batch_alter_table('blue_lines', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('metadata', sa.JSON(), nullable=True))
    
    # Copy data from old column to new (outside batch to ensure column exists)
    op.execute('UPDATE blue_lines SET metadata = calculation_metadata WHERE calculation_metadata IS NOT NULL')
    
    with op.batch_alter_table('blue_lines', recreate='always') as batch_op:
        batch_op.drop_column('calculation_metadata')
    
    # Clean up old composite columns that are no longer needed
    with op.batch_alter_table('composites') as batch_op:
        batch_op.drop_index('ix_composites_is_blue_line')
        batch_op.drop_column('supplier_reference')
        batch_op.drop_column('blue_line_fields')
        batch_op.drop_column('is_blue_line')
    
    # Clean up old materials column and add index
    with op.batch_alter_table('materials') as batch_op:
        batch_op.create_index(op.f('ix_materials_sap_status'), ['sap_status'], unique=False)
        batch_op.drop_column('lluch_supplier_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Commented out ALTER COLUMN operations as SQLite doesn't support them
    # op.alter_column('approval_workflows', 'regulatory_status',
    #            existing_type=sa.String(length=20),
    #            type_=sa.VARCHAR(length=50),
    #            existing_nullable=True)
    # op.alter_column('approval_workflows', 'technical_status',
    #            existing_type=sa.String(length=20),
    #            type_=sa.VARCHAR(length=50),
    #            existing_nullable=True)
    
    # Restore old column names and structure
    with op.batch_alter_table('blue_lines') as batch_op:
        batch_op.add_column(sa.Column('calculation_metadata', sqlite.JSON(), nullable=True))
        op.execute('UPDATE blue_lines SET calculation_metadata = metadata')
        batch_op.drop_column('metadata')
    
    with op.batch_alter_table('composites') as batch_op:
        batch_op.add_column(sa.Column('is_blue_line', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False))
        batch_op.add_column(sa.Column('blue_line_fields', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('supplier_reference', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_index('ix_composites_is_blue_line', ['is_blue_line'], unique=False)
    
    with op.batch_alter_table('materials') as batch_op:
        batch_op.add_column(sa.Column('lluch_supplier_code', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_index(op.f('ix_materials_sap_status'))
    # ### end Alembic commands ###






